version: "3.0"
services:
  database:
    image: container-registry.oracle.com/database/free
    environment:
      # - ORACLE_SID=xe
      - ORACLE_PWD=Oracle123!
    ports:
      - 1888:1521
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 8192M
        reservations:
            cpus: "0.4"
          memory: 4096M
